package jh.inspectedpost

import jh.common.OperationType
import jh.post.model.Post
import java.time.LocalDateTime

data class InspectPostMessage(
    val id: Long,
    val payload: Payload?,
    val operationType: OperationType,
) {

    data class Payload(
        val post: Post,
        val categoryName: String,
        val autoGeneratedTags: List<String>,
        val inspectedAt: LocalDateTime
    )
}
