package jh.inspectedpost

import com.fasterxml.jackson.core.JsonProcessingException
import com.fasterxml.jackson.databind.ObjectMapper
import jh.InspectedPostMessageProducePort
import jh.common.OperationType
import jh.common.Topic.Companion.INSPECTED_TOPIC
import jh.inspected.InspectedPost
import jh.originalpost.OriginalPostMessage
import jh.post.model.Post
import org.springframework.kafka.core.KafkaTemplate
import org.springframework.stereotype.Component

@Component
class InspectedPostMessageProduceAdapter(
    private val kafkaTemplate: KafkaTemplate<String, Any>,
    private val objectMapper: ObjectMapper, // TODO: CustomObjectMapper
) : InspectedPostMessageProducePort {

    override fun sendCreateMessage(inspectedPost: InspectedPost) {
        val inspectedPostMessage = InspectPostMessage(
            id = inspectedPost.post.id!!,
            payload = InspectPostMessage.Payload(
                post = inspectedPost.post,
                categoryName = inspectedPost.categoryName,
                autoGeneratedTags = inspectedPost.autoGeneratedTags,
                inspectedAt = inspectedPost.inspectedAt,
            ),
            operationType = OperationType.CREATE,
        )

        this.sendMessage(inspectedPostMessage)
    }

    override fun sendUpdateMessage(inspectedPost: InspectedPost) {
        val inspectedPostMessage = InspectPostMessage(
            id = inspectedPost.post.id!!,
            payload = InspectPostMessage.Payload(
                post = inspectedPost.post,
                categoryName = inspectedPost.categoryName,
                autoGeneratedTags = inspectedPost.autoGeneratedTags,
                inspectedAt = inspectedPost.inspectedAt,
            ),
            operationType = OperationType.UPDATE,
        )

        this.sendMessage(inspectedPostMessage)
    }

    override fun sendDeleteMessage(postId: Long) {
        val message = InspectPostMessage(postId, null, OperationType.DELETE)

        this.sendMessage(message)
    }

    private fun sendMessage(message: InspectPostMessage) {
        try {
            kafkaTemplate.send(INSPECTED_TOPIC, message.id.toString(), objectMapper.writeValueAsString(message))
            println("[InspectedPostMessageProduceAdapter] Message sent successfully: ${objectMapper.writeValueAsString(message)}")
        } catch (e: JsonProcessingException) {
            throw RuntimeException(e)
        }
    }

    private fun convertToMessage(id: Long?, post: Post?, operationType: OperationType): OriginalPostMessage {
        return OriginalPostMessage(
            id = id!!,
            payload = post?.let {
                OriginalPostMessage.Payload(
                    it.id,
                    it.title,
                    it.content,
                    it.userId,
                    it.categoryId,
                    it.createdAt,
                    it.updatedAt,
                    it.deletedAt
                )
            },
            operationType = operationType
        )
    }
}

