package jh.inspected

import jh.post.model.Post
import java.time.LocalDateTime

data class InspectedPost(
    val post: Post,
    val categoryName: String,
    val autoGeneratedTags: List<String>,
    val inspectedAt: LocalDateTime
) {
    companion object {
        fun generate(
            post: Post,
            categoryName: String,
            autoGeneratedTags: List<String>,
        ): InspectedPost {
            return InspectedPost(
                post = post,
                categoryName = categoryName,
                autoGeneratedTags = autoGeneratedTags,
                inspectedAt = LocalDateTime.now()
            )
        }
    }
}
