package jh.post

import jh.inspected.InspectedPost

class PostDocumentConverter {

    companion object {
        fun toDocument(inspectedPost: InspectedPost): PostDocument {
            val post = inspectedPost.post
            return PostDocument(
                id = post.id!!,
                title = post.title,
                content = post.content,
                categoryName = inspectedPost.categoryName,
                tags = inspectedPost.autoGeneratedTags.toMutableList(),
                indexedAt = inspectedPost.inspectedAt
            )
        }
    }
}
